#
# Module manifest for module 'PS-AutomationHelper'
#
# Generated by: gfa
#
# Generated on: 12/29/2022
#

@{

  # Script module or binary module file associated with this manifest.
  RootModule        = './PS-AutomationHelper.psm1'

  # Version number of this module.
  ModuleVersion     = '0.0.2'

  # Supported PSEditions
  # CompatiblePSEditions = @()

  # ID used to uniquely identify this module
  GUID              = '078d6da9-c523-49f2-9376-9f07eb5b39f7'

  # Author of this module
  Author            = 'gfa@root.ch'

  # Company or vendor of this module
  CompanyName       = 'root-service ag'

  # Copyright statement for this module
  Copyright         = '(c) 2023 root-service (Fabian Gygax). All rights reserved.'

  # Description of the functionality provided by this module
  Description       = 'Helper module for automating tasks.'

  # Minimum version of the PowerShell engine required by this module
  PowerShellVersion = '7.0'

  # Name of the PowerShell host required by this module
  # PowerShellHostName = ''

  # Minimum version of the PowerShell host required by this module
  # PowerShellHostVersion = ''

  # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
  # DotNetFrameworkVersion = ''

  # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
  # ClrVersion = ''

  # Processor architecture (None, X86, Amd64) required by this module
  # ProcessorArchitecture = ''

  # Modules that must be imported into the global environment prior to importing this module
  # RequiredModules = @()

  # Assemblies that must be loaded prior to importing this module
  # RequiredAssemblies = @()

  # Script files (.ps1) that are run in the caller's environment prior to importing this module.
  # ScriptsToProcess = @()

  # Type files (.ps1xml) to be loaded when importing this module
  # TypesToProcess = @()

  # Format files (.ps1xml) to be loaded when importing this module
  # FormatsToProcess = @()

  # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
  # NestedModules = @()

  # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
  FunctionsToExport = @('Add-ExecutionStep', 'Invoke-Execution', 'New-ExecutionStep')

  # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
  CmdletsToExport   = @()

  # Variables to export from this module
  VariablesToExport = '*'

  # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
  AliasesToExport   = @()

  # DSC resources to export from this module
  # DscResourcesToExport = @()

  # List of all modules packaged with this module
  # ModuleList = @()

  # List of all files packaged with this module
  # FileList = @()

  # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
  PrivateData       = @{

    PSData = @{

      # Tags applied to this module. These help with module discovery in online galleries.
      Tags                       = @('Automation', 'PowerShell')

      # A URL to the license for this module.
      LicenseUri                 = 'https://github.com/root-service/PS-AutomationHelper/blob/main/LICENSE'

      # A URL to the main website for this project.
      ProjectUri                 = 'https://github.com/root-service/PS-AutomationHelper'

      # A URL to an icon representing this module.
      # IconUri = ''

      # ReleaseNotes of this module
      ReleaseNotes               = 'https://github.com/root-service/PS-AutomationHelper/blob/main/ReleaseNotes.md'

      # Prerelease string of this module
      Prerelease                 = 'rc-1'

      # Flag to indicate whether the module requires explicit user acceptance for install/update/save
      RequireLicenseAcceptance   = $false

      # External dependent modules of this module
      ExternalModuleDependencies = @()

    } # End of PSData hashtable

  } # End of PrivateData hashtable

  # HelpInfo URI of this module
  HelpInfoURI       = 'https://github.com/root-service/PS-AutomationHelper/blob/main/README.md'

  # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
  # DefaultCommandPrefix = ''

}

